from setuptools import setup, find_packages

setup(
    name="bots",
    version="1.0.0",
    author="srcsdk",
    description="trading bot strategies and technical analysis",
    long_description=open("readme.md").read(),
    long_description_content_type="text/markdown",
    url="https://pypi.org/project/bots/",
    packages=find_packages(),
    py_modules=[
        "ohlc",
        "indicators",
        "gui",
        "gapup",
        "bcross",
        "across",
        "movo",
        "reta",
        "vested",
        "current",
        "hype",
        "wsb",
        "portfolio",
        "correlation",
        "risk",
        "backtest",
        "scanner",
        "pairs",
        "multiframe",
        "var",
        "alerts",
        "meanrev",
        "strength",
        "ichimoku",
        "fibonacci",
        "montecarlo",
        "kelly",
        "performance",
        "compare",
        "watchlist",
    ],
    python_requires=">=3.7",
    install_requires=[
        "matplotlib",
    ],
    entry_points={
        "console_scripts": [
            "bots-gui=gui:main",
            "bots-gapup=gapup:scan",
            "bots-bcross=bcross:scan",
            "bots-movo=movo:scan_movo",
            "bots-reta=reta:analyze_ticker",
            "bots-hype=hype:main",
            "bots-vested=vested:analyze",
            "bots-current=current:get_fear_greed",
        ],
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
